# Generated by Django 4.1.6 on 2023-02-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_item_category_item_label_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(default="test"),
            preserve_default=False,
        ),
    ]
