# Generated by Django 4.1.6 on 2023-02-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_item_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
