# Generated by Django 4.1.6 on 2023-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
