# Generated by Django 4.1.6 on 2023-02-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_item_quantity_orderitem_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="orered_date",
            new_name="ordered_date",
        ),
    ]
