# Generated by Django 4.1.6 on 2023-02-07 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0010_alter_orderitem_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAdress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_adress", models.CharField(max_length=100)),
                ("apartment_adress", models.CharField(max_length=100)),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=746, multiple=True),
                ),
                ("postcode", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
