# Generated by Django 4.1.6 on 2023-02-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_billingadress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingadress",
            old_name="apartment_adress",
            new_name="apartment_address",
        ),
        migrations.RenameField(
            model_name="billingadress",
            old_name="street_adress",
            new_name="street_address",
        ),
    ]
