# Generated by Django 4.1.6 on 2023-02-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_item_image_alter_billingaddress_country_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
